let candidateData=[],sid,seconds=0,clock,handsFree=false,recognition;
const $=s=>document.querySelector(s),chat=$('#chat');
async function load(){try{const r=await fetch('/api/candidates');candidateData=(await r.json()).candidates||[];$('#candidates').innerHTML=candidateData.map((c,i)=>`<option value="${i}">${c.member.name} · ${c.member.jobRole}</option>`).join('')}catch{$('#candidates').innerHTML='<option>Use the API with a candidate payload</option>'}}
function setVoice(state,text){const bar=$('#voiceBar');bar.className='voicebar '+state;$('#voiceState').textContent=text}
function speak(text){if(!handsFree||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();setVoice('speaking','Orbit is asking…');const u=new SpeechSynthesisUtterance(text.replace(/Day \d+ ·[^\n]*\n\n?/,''));u.rate=.98;u.pitch=1.04;u.onend=()=>listen(true);u.onerror=()=>setVoice('','Voice playback ended — use the mic to reply.');window.speechSynthesis.speak(u)}
function add(text,user=false){const d=document.createElement('div');d.className='message '+(user?'user':'agent');d.innerHTML=`<div class="avatar">${user?'YOU':'✦'}</div><div><div class="meta">${user?'CANDIDATE':'ORBIT INTERVIEWER'}</div><div class="bubble"></div></div>`;d.querySelector('.bubble').textContent=text;chat.append(d);chat.scrollTop=chat.scrollHeight;if(!user)speak(text)}
async function request(payload){const r=await fetch('/api/interview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.json()}
$('#start').onclick=async()=>{const candidate=candidateData[$('#candidates').value];if(!candidate)return;sid=crypto.randomUUID();$('#session').textContent=sid.slice(0,8).toUpperCase();$('#empty').classList.add('hidden');chat.classList.remove('hidden');$('#voiceBar').classList.remove('hidden');$('#composer').classList.remove('hidden');$('#candidatePicker').style.opacity='.45';$('#start').disabled=true;add((await request({sessionId:sid,candidate})).reply);clock=setInterval(()=>{$('#timer').textContent=new Date(++seconds*1000).toISOString().slice(14,19)},1000)};
async function send(){const text=$('#answer').value.trim();if(!text||!sid)return;$('#answer').value='';add(text,true);$('#send').disabled=true;setVoice('','Orbit is thinking…');const res=await request({sessionId:sid,message:text});$('#send').disabled=false;if(res.done){clearInterval(clock);handsFree=false;window.speechSynthesis?.cancel();$('#composer').classList.add('hidden');$('#voiceBar').classList.add('hidden');showReport(res.feedback)}else add(res.reply)}
function listen(auto=false){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Speech recognition is not available in this browser.');try{recognition?.abort()}catch{}const r=recognition=new SR();r.lang='en-US';r.interimResults=true;r.continuous=false;let final='';r.onstart=()=>setVoice('listening','Listening — speak naturally');r.onresult=e=>{final=Array.from(e.results).map(x=>x[0].transcript).join(' ');$('#answer').value=final};r.onend=()=>{if(final.trim())send();else if(auto&&handsFree)setVoice('','I didn’t catch that — tap the mic and try again.');else setVoice('','Voice mode ready')};r.onerror=()=>setVoice('','Microphone unavailable — use text input.');r.start()}
function showReport(f){$('#report').classList.remove('hidden');$('#report').innerHTML=`<div class="eyebrow">INTERVIEW COMPLETE</div><h2>Your engineering narrative</h2><p>${f.summary}</p><div class="report-grid">${[['Strengths',f.strengths],['Growth edges',f.gaps],['Next rehearsal',f.next]].map(([h,a])=>`<div class="card"><h3>${h}</h3><ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div>`}
$('#send').onclick=send;$('#answer').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#mic').onclick=()=>listen(false);
$('#voiceToggle').onclick=()=>{if(!(window.SpeechRecognition||window.webkitSpeechRecognition)||!('speechSynthesis'in window)){setVoice('','Voice mode needs Chrome or Edge with microphone access.');return}handsFree=!handsFree;$('#voiceToggle').textContent=handsFree?'Disable hands-free':'Enable hands-free';if(handsFree){const b=chat.querySelector('.message.agent:last-child .bubble');if(b)speak(b.textContent)}else{window.speechSynthesis.cancel();try{recognition?.abort()}catch{}setVoice('','Voice mode paused')}};load();
